import {
  DashboardOutlined,
  ShoppingCartOutlined,
  ShoppingOutlined,
  UserOutlined,
  PictureOutlined,
  GiftOutlined,
  ShopOutlined,
  TeamOutlined,
  MailOutlined,
  SettingOutlined,
  MobileOutlined,
  FileOutlined,
} from "@ant-design/icons";
import { APP_PREFIX_PATH } from "configs/AppConfig";

const mainTree = [
  {
    key: "home",
    path: `${APP_PREFIX_PATH}/home`,
    title: "Основное",
    icon: "",
    breadcrumb: false,
    submenu: [
      {
        key: "home",
        path: `${APP_PREFIX_PATH}/board`,
        title: "Дашборд",
        icon: DashboardOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "catalog",
        path: `${APP_PREFIX_PATH}/catalog`,
        title: "Католог",
        icon: ShoppingCartOutlined,
        breadcrumb: true,
        submenu: [
          {
            key: "goods",
            path: `${APP_PREFIX_PATH}/catalog/goods`,
            title: "Товары",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "category",
            path: `${APP_PREFIX_PATH}/catalog/category`,
            title: "Категории",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "collection",
            path: `${APP_PREFIX_PATH}/catalog/collection`,
            title: "Коллекции",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "combo",
            path: `${APP_PREFIX_PATH}/catalog/combo`,
            title: "Комбо",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
        ],
      },
      {
        key: "basket",
        path: `${APP_PREFIX_PATH}/basket`,
        title: "Заказы",
        icon: ShoppingOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "clients",
        path: `${APP_PREFIX_PATH}/clients`,
        title: "Клиенты",
        icon: UserOutlined,
        breadcrumb: false,
        submenu: [
          {
            key: "clients-list",
            path: `${APP_PREFIX_PATH}/clients/clients-list`,
            title: "Список клиентов",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "clients-group",
            path: `${APP_PREFIX_PATH}/clients/clients-group`,
            title: "Группы клиентов",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
        ],
      },
      {
        key: "banner",
        path: `${APP_PREFIX_PATH}/banner`,
        title: "Баннеры",
        icon: PictureOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "gifts",
        path: `${APP_PREFIX_PATH}/gifts`,
        title: "Промокод",
        icon: GiftOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "offline",
        path: `${APP_PREFIX_PATH}/offline`,
        title: "Точки",
        icon: ShopOutlined,
        breadcrumb: false,
        submenu: [
          {
            key: "offline_address",
            path: `${APP_PREFIX_PATH}/offline_address`,
            title: "Адреса",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "offline_geozone",
            path: `${APP_PREFIX_PATH}/offline_geozone`,
            title: "Геозоны",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
        ],
      },
      {
        key: "ppl",
        path: `${APP_PREFIX_PATH}/ppl`,
        title: "Сотрудники",
        icon: TeamOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "mail",
        path: `${APP_PREFIX_PATH}/mail`,
        title: "Рассылки",
        icon: MailOutlined,
        breadcrumb: false,
        submenu: [],
      },
    ],
  },
];
const systemTree = [
  {
    key: "system",
    path: `${APP_PREFIX_PATH}/system`,
    title: "Системное",
    icon: "",
    breadcrumb: false,
    submenu: [
      {
        key: "setting",
        path: `${APP_PREFIX_PATH}/system/setting`,
        title: "Настройки",
        icon: SettingOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "mobile",
        path: `${APP_PREFIX_PATH}/system/mobile`,
        title: "Мобильное Приложение",
        icon: MobileOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "logs",
        path: `${APP_PREFIX_PATH}/system/logs`,
        title: "Логи",
        icon: FileOutlined,
        breadcrumb: false,
        submenu: [],
      },
    ],
  },
];

const navigationConfig = [...mainTree, ...systemTree];

export default navigationConfig;
